### ISSUE TITLE
Invalid UserCSS format

### ISSUE THREAD

**Issue by vednoc** [Irilith/irisproject#1]
Hi Lilith,

I noticed that your userstyle can't be installed from USw. Here is how you can fix that:

```css
/* ==UserStyle==
@name         HoYoLab Dark Theme
@namespace    https://github.com/Irilith/irisproject.github.io
@version      1.0.0
@author       Lilith Iris#7707
==/UserStyle== */

@-moz-document domain("hoyolab.com") {
  @import url("https://irilith.github.io/irisproject/Theme/HoYoLab/hoyolabdarktheme.css");
}
```

Unless there's a specific reason for having two separate userstyles, you should combine them into one. If you go for that, rename `hoyolabdarktheme.css` to `hoyolabdarktheme.user.css` in order to install it from GitHub (or anywhere else, really). You can then set the raw URL as "Mirror source code URL" on USw, and it will be mirrored automatically multiple times per day. See [Stylus' wiki on Writing UserCSS][1] and/or feel free to ask if you need help.

[1]: https://github.com/openstyles/stylus/wiki/Writing-UserCSS

**Comment by Irilith** [comment]
I dont know, thanks for telling me
Im new on USw and dont really know about it i just post it but my original doesnt have `@-moz-document ` and the website just add itself i think its fine or something anyway ive change like you said thank for telling me
(My grammar is bad hope you can understand)

**Comment by vednoc** [comment]
No worries, your grammar is good.

UserCSS format requires that `@name`, `@namespace`, and `version` are available. In your case, `@version` is still invalid (try to install it from USw and you'll see the error on install page). As for `@-moz-document`, all UserCSS styles without it will apply globally. The way that it's set up right now is good, but if you only had `@import url("...")` then it would be a global userstyle, and that isn't what you want.

P.S. If you need help, the best way is to join Styuls' or USw's Discord. We're always willing to help newcomers.

**Comment by Irilith** [comment]
I think its good now, im currently using phone so i dont know if its still bug but i clicked install and its show me the code i guess that ok? 
I'll join USw's discord tomorrow. 
Thanks.

**Comment by vednoc** [comment]
It does look good now. Thank you for fixing it. 🎉
